ARG REGISTRY_URL
ARG BASE_IMAGE
FROM ${REGISTRY_URL}/${BASE_IMAGE}
LABEL baseImage=${BASE_IMAGE}

ARG FILE_PATH
COPY ${FILE_PATH} /application.jar
ARG JAVA_OPTIONS
ENV JAVA_OPTIONS ${JAVA_OPTIONS}
ARG DEFAULT_JVM_OPTIONS
ENV DEFAULT_JVM_OPTIONS ${DEFAULT_JVM_OPTIONS}
ENV DEFAULT_JAVA_OPTIONS -Dspring.profiles.active=${ENV} -Dfile.encoding=UTF8 -Djava.util.concurrent.ForkJoinPool.common.parallelism=1

CMD java -version ; java -jar ${DEFAULT_JVM_OPTIONS} ${DEFAULT_JAVA_OPTIONS} ${JAVA_OPTIONS} /application.jar